Assuming unrestricted shared filesystem usage.
Building DAG of jobs...
Your conda installation is not configured to use strict channel priorities. This is however crucial for having robust and correct environments (for details, see https://conda-forge.org/docs/user/tipsandtricks.html). Please consider to configure strict priorities by executing 'conda config --set channel_priority strict'.
Using shell: /usr/bin/bash
Provided cores: 2
Rules claiming more threads will be scaled down.
Job stats:
job              count
-------------  -------
all                  1
kmean_cluster        3
total                4

Select jobs to execute...
Execute 2 jobs...

[Fri Feb 21 01:03:11 2025]
localrule kmean_cluster:
    input: data/processed/momo/all_features_clean.csv
    output: data/output/momo/kmeans_cluster.csv
    jobid: 12
    reason: Code has changed since last execution
    wildcards: study=momo
    resources: tmpdir=/tmp

[Fri Feb 21 01:03:11 2025]
localrule kmean_cluster:
    input: data/processed/tesserae/all_features_clean.csv
    output: data/output/tesserae/kmeans_cluster.csv
    jobid: 11
    reason: Missing output files: data/output/tesserae/kmeans_cluster.csv
    wildcards: study=tesserae
    resources: tmpdir=/tmp

Activating conda environment: .snakemake/conda/1487a308532d405478836fe525175bd3_
Activating conda environment: .snakemake/conda/1487a308532d405478836fe525175bd3_
Activating conda environment: .snakemake/conda/1487a308532d405478836fe525175bd3_
Activating conda environment: .snakemake/conda/1487a308532d405478836fe525175bd3_
[Fri Feb 21 01:04:15 2025]
Finished job 12.
1 of 4 steps (25%) done
Select jobs to execute...
Execute 1 jobs...

[Fri Feb 21 01:04:15 2025]
localrule kmean_cluster:
    input: data/processed/globem/all_features_clean.csv
    output: data/output/globem/kmeans_cluster.csv
    jobid: 13
    reason: Missing output files: data/output/globem/kmeans_cluster.csv
    wildcards: study=globem
    resources: tmpdir=/tmp

Activating conda environment: .snakemake/conda/1487a308532d405478836fe525175bd3_
Activating conda environment: .snakemake/conda/1487a308532d405478836fe525175bd3_
Traceback (most recent call last):
  File "/scratch/work/luongn1/digirhythm-v2/.snakemake/scripts/tmpz93uhg4p.kmeans.py", line 65, in <module>
    main(snakemake.input, snakemake.output,  snakemake.params)
    ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/work/luongn1/digirhythm-v2/.snakemake/scripts/tmpz93uhg4p.kmeans.py", line 56, in main
    data['Cluster'] = best_labels
    ~~~~^^^^^^^^^^^
  File "/scratch/work/luongn1/digirhythm-v2/.snakemake/conda/1487a308532d405478836fe525175bd3_/lib/python3.13/site-packages/pandas/core/frame.py", line 4311, in __setitem__
    self._set_item(key, value)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/scratch/work/luongn1/digirhythm-v2/.snakemake/conda/1487a308532d405478836fe525175bd3_/lib/python3.13/site-packages/pandas/core/frame.py", line 4524, in _set_item
    value, refs = self._sanitize_column(value)
                  ~~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "/scratch/work/luongn1/digirhythm-v2/.snakemake/conda/1487a308532d405478836fe525175bd3_/lib/python3.13/site-packages/pandas/core/frame.py", line 5266, in _sanitize_column
    com.require_length_match(value, self.index)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/scratch/work/luongn1/digirhythm-v2/.snakemake/conda/1487a308532d405478836fe525175bd3_/lib/python3.13/site-packages/pandas/core/common.py", line 573, in require_length_match
    raise ValueError(
    ...<4 lines>...
    )
ValueError: Length of values (25380) does not match length of index (25386)
RuleException:
CalledProcessError in file /scratch/work/luongn1/digirhythm-v2/workflow/rules/embeddings.smk, line 23:
Command 'source /appl/scibuilder-mamba/aalto-rhel9/prod/software/mamba/2024-01/39cf5e1/bin/activate '/scratch/work/luongn1/digirhythm-v2/.snakemake/conda/1487a308532d405478836fe525175bd3_'; set -euo pipefail;  python /scratch/work/luongn1/digirhythm-v2/.snakemake/scripts/tmpz93uhg4p.kmeans.py' returned non-zero exit status 1.
[Fri Feb 21 01:06:03 2025]
Error in rule kmean_cluster:
    jobid: 13
    input: data/processed/globem/all_features_clean.csv
    output: data/output/globem/kmeans_cluster.csv
    conda-env: /scratch/work/luongn1/digirhythm-v2/.snakemake/conda/1487a308532d405478836fe525175bd3_

Traceback (most recent call last):
  File "/scratch/work/luongn1/digirhythm-v2/.snakemake/scripts/tmpifjciihu.kmeans.py", line 65, in <module>
    main(snakemake.input, snakemake.output,  snakemake.params)
    ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/work/luongn1/digirhythm-v2/.snakemake/scripts/tmpifjciihu.kmeans.py", line 56, in main
    data['Cluster'] = best_labels
    ~~~~^^^^^^^^^^^
  File "/scratch/work/luongn1/digirhythm-v2/.snakemake/conda/1487a308532d405478836fe525175bd3_/lib/python3.13/site-packages/pandas/core/frame.py", line 4311, in __setitem__
    self._set_item(key, value)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/scratch/work/luongn1/digirhythm-v2/.snakemake/conda/1487a308532d405478836fe525175bd3_/lib/python3.13/site-packages/pandas/core/frame.py", line 4524, in _set_item
    value, refs = self._sanitize_column(value)
                  ~~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "/scratch/work/luongn1/digirhythm-v2/.snakemake/conda/1487a308532d405478836fe525175bd3_/lib/python3.13/site-packages/pandas/core/frame.py", line 5266, in _sanitize_column
    com.require_length_match(value, self.index)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/scratch/work/luongn1/digirhythm-v2/.snakemake/conda/1487a308532d405478836fe525175bd3_/lib/python3.13/site-packages/pandas/core/common.py", line 573, in require_length_match
    raise ValueError(
    ...<4 lines>...
    )
ValueError: Length of values (106598) does not match length of index (106606)
RuleException:
CalledProcessError in file /scratch/work/luongn1/digirhythm-v2/workflow/rules/embeddings.smk, line 23:
Command 'source /appl/scibuilder-mamba/aalto-rhel9/prod/software/mamba/2024-01/39cf5e1/bin/activate '/scratch/work/luongn1/digirhythm-v2/.snakemake/conda/1487a308532d405478836fe525175bd3_'; set -euo pipefail;  python /scratch/work/luongn1/digirhythm-v2/.snakemake/scripts/tmpifjciihu.kmeans.py' returned non-zero exit status 1.
[Fri Feb 21 01:36:19 2025]
Error in rule kmean_cluster:
    jobid: 11
    input: data/processed/tesserae/all_features_clean.csv
    output: data/output/tesserae/kmeans_cluster.csv
    conda-env: /scratch/work/luongn1/digirhythm-v2/.snakemake/conda/1487a308532d405478836fe525175bd3_

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2025-02-21T010307.614567.snakemake.log
WorkflowError:
At least one job did not complete successfully.
